version: '3'
services:
  backend:
    restart: always
    container_name: blogsite-back
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
        #depends_on:
        #      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    restart: always
    container_name: blogsite-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # env_file:
    #   - ./frontend/.env
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      # - /app/node_modules

        # db:
        # image: postgres:13
        #    container_name: blogsite-db
        #    environment:
        #      POSTGRES_USER: ${POSTGRES_USER}
        #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        #      POSTGRES_DB: ${POSTGRES_DB}
        #    env_file:
        #      - ./backend/.env
        # required: "true"
        #    ports:
        #      - "5433:5432"
        #    volumes:
        #      - postgres_data:/var/lib/postgresql/data
        #    command: ["postgres", "-c", "port=5433"]


        #volumes:
        #:  postgres_data:
