services:
  - type: web
    name: blogsite
    env: docker
    plan: free
    repo: https://github.com/Hasmik-icml/blog-site
    branch: master
    dockerfilePath: ./Dockerfile
    buildCommand: docker-compose up -d --build
    # startCommand: docker-compose up
    envVars:
      - key: DATABASE_URL
        fromGroup: blogsite-env
      - key: POSTGRES_USER
        fromGroup: blogsite-env
      - key: POSTGRES_PASSWORD
        fromGroup: blogsite-env
      - key: POSTGRES_DB
        fromGroup: blogsite-env
    mounts:
      - type: volume
        name: pg_data
        mountPath: /var/lib/postgresql/data

volumes:
  - name: pg_data
