services:
  - type: web
    name: backend
    env: docker
    plan: free
    buildCommand: docker-compose -f docker-compose.yml build backend
    startCommand: docker-compose -f docker-compose.yml up backend
    repo: https://github.com/Hasmik-icml/blog-site
    branch: master
    envVars:
      - key: DATABASE_URL
        fromGroup: blogsite-env
      - key: POSTGRES_USER
        fromGroup: blogsite-env
      - key: POSTGRES_PASSWORD
        fromGroup: blogsite-env
      - key: POSTGRES_DB
        fromGroup: blogsite-env
    mounts:
      - type: volume
        name: pg_data
        mountPath: /var/lib/postgresql/data

  - type: web
    name: frontend
    env: docker
    plan: free
    buildCommand: docker-compose -f docker-compose.yml build frontend
    startCommand: docker-compose -f docker-compose.yml up frontend
    repo: https://github.com/Hasmik-icml/blog-site
    branch: master

  - type: private-service
    name: db
    env: docker
    plan: free
    image: postgres:13
    envVars:
      - key: POSTGRES_USER
        fromGroup: blogsite-env
      - key: POSTGRES_PASSWORD
        fromGroup: blogsite-env
      - key: POSTGRES_DB
        fromGroup: blogsite-env
    mounts:
      - type: volume
        name: pg_data
        mountPath: /var/lib/postgresql/data

volumes:
  - name: pg_data
