version: '3'
services:
  backend:
    restart: always
    container_name: blogsite-back
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3010:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${URL}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    restart: always
    container_name: blogsite-front
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13
    container_name: blogsite-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
